# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    TWILIO_SID: '%env(TWILIO_SID)%'
    TWILIO_AUTH_TOKEN: '%env(TWILIO_AUTH_TOKEN)%'
    TWILIO_PHONE_NUMBER: '%env(TWILIO_PHONE_NUMBER)%'
    MY_PHONE_NUMBER: '%env(MY_PHONE_NUMBER)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service for Twilio integration
    App\Service\SmsService:
        arguments:
            $twilioSid: '%env(TWILIO_SID)%'
            $twilioToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioFrom: '%env(TWILIO_PHONE_NUMBER)%'
